import type {
  ApplicationWithDriver,
  Conversation,
  DashboardKpis,
  Driver,
  Load,
  Notification,
  Payment,
  Review,
  TrackingEvent,
  Vehicle,
  ChartPoint,
  MapMarker,
} from '@/types'

const now = new Date()
const iso = (daysAgo: number) =>
  new Date(now.getTime() - daysAgo * 24 * 60 * 60 * 1000).toISOString()

export const mockKpis: DashboardKpis = {
  activeLoads: 24,
  openApplications: 18,
  completedTrips: 142,
  monthlyRevenue: 186450,
  averageRating: 4.8,
  unreadMessages: 5,
}

export const mockRevenueChart: ChartPoint[] = [
  { label: 'Jan', value: 82000 },
  { label: 'Fev', value: 91000 },
  { label: 'Mar', value: 105000 },
  { label: 'Abr', value: 98000 },
  { label: 'Mai', value: 124000 },
  { label: 'Jun', value: 141000 },
  { label: 'Jul', value: 156000 },
  { label: 'Ago', value: 186450 },
]

export const mockLoadsChart: ChartPoint[] = [
  { label: 'Seg', value: 12 },
  { label: 'Ter', value: 18 },
  { label: 'Qua', value: 15 },
  { label: 'Qui', value: 22 },
  { label: 'Sex', value: 28 },
  { label: 'Sáb', value: 14 },
  { label: 'Dom', value: 9 },
]

export const mockLoads: Load[] = [
  {
    id: '1',
    company_id: 'c1',
    title: 'Soja a granel — 30 toneladas',
    description: 'Coleta em silo, descarga em terminal portuário. Documentação liberada.',
    origin_city: 'Rondonópolis',
    origin_state: 'MT',
    destination_city: 'Santos',
    destination_state: 'SP',
    cargo_type: 'Granel',
    weight_kg: 30000,
    price: 12500,
    vehicle_type: 'Carreta',
    pickup_date: iso(-1),
    delivery_date: null,
    status: 'open',
    applications_count: 7,
    company: { trade_name: 'AgroSul Logística', rating_avg: 4.9, logo_url: null },
    created_at: iso(2),
    updated_at: iso(1),
    deleted_at: null,
  },
  {
    id: '2',
    company_id: 'c2',
    title: 'Container refrigerado 40ft',
    description: 'Carga frigorificada. Temperatura controlada obrigatória.',
    origin_city: 'Curitiba',
    origin_state: 'PR',
    destination_city: 'Campinas',
    destination_state: 'SP',
    cargo_type: 'Frigorificado',
    weight_kg: 18000,
    price: 4800,
    vehicle_type: 'Carreta',
    pickup_date: iso(0),
    delivery_date: null,
    status: 'open',
    applications_count: 4,
    company: { trade_name: 'ColdTrack BR', rating_avg: 4.7, logo_url: null },
    created_at: iso(1),
    updated_at: iso(0),
    deleted_at: null,
  },
  {
    id: '3',
    company_id: 'c1',
    title: 'Móveis industriais',
    description: 'Carga seca paletizada. Acesso por rampa no destino.',
    origin_city: 'Joinville',
    origin_state: 'SC',
    destination_city: 'Belo Horizonte',
    destination_state: 'MG',
    cargo_type: 'Carga seca',
    weight_kg: 8500,
    price: 3200,
    vehicle_type: 'Truck',
    pickup_date: iso(-3),
    delivery_date: iso(-1),
    status: 'in_progress',
    applications_count: 12,
    company: { trade_name: 'AgroSul Logística', rating_avg: 4.9, logo_url: null },
    created_at: iso(5),
    updated_at: iso(1),
    deleted_at: null,
  },
  {
    id: '4',
    company_id: 'c3',
    title: 'Autopeças urgentes',
    description: 'Entrega express. Preferência para motoristas com histórico 5★.',
    origin_city: 'São Paulo',
    origin_state: 'SP',
    destination_city: 'Rio de Janeiro',
    destination_state: 'RJ',
    cargo_type: 'Carga seca',
    weight_kg: 2200,
    price: 1800,
    vehicle_type: 'VUC',
    pickup_date: iso(0),
    delivery_date: null,
    status: 'open',
    applications_count: 3,
    company: { trade_name: 'PartsMove', rating_avg: 4.6, logo_url: null },
    created_at: iso(0),
    updated_at: iso(0),
    deleted_at: null,
  },
  {
    id: '5',
    company_id: 'c2',
    title: 'Açúcar cristal — 28t',
    description: 'Rota regular semanal. Pagamento em até 7 dias após descarga.',
    origin_city: 'Ribeirão Preto',
    origin_state: 'SP',
    destination_city: 'Porto Alegre',
    destination_state: 'RS',
    cargo_type: 'Granel',
    weight_kg: 28000,
    price: 9800,
    vehicle_type: 'Bitrem',
    pickup_date: iso(-10),
    delivery_date: iso(-7),
    status: 'completed',
    applications_count: 9,
    company: { trade_name: 'ColdTrack BR', rating_avg: 4.7, logo_url: null },
    created_at: iso(12),
    updated_at: iso(7),
    deleted_at: null,
  },
  {
    id: '6',
    company_id: 'c3',
    title: 'Eletrodomésticos',
    description: 'Carga frágil. Embalagem reforçada. Seguro incluso.',
    origin_city: 'Manaus',
    origin_state: 'AM',
    destination_city: 'Brasília',
    destination_state: 'DF',
    cargo_type: 'Carga seca',
    weight_kg: 12000,
    price: 14500,
    vehicle_type: 'Carreta',
    pickup_date: iso(-2),
    delivery_date: null,
    status: 'open',
    applications_count: 5,
    company: { trade_name: 'PartsMove', rating_avg: 4.6, logo_url: null },
    created_at: iso(3),
    updated_at: iso(2),
    deleted_at: null,
  },
]

export const mockDrivers: Driver[] = [
  {
    id: 'd1',
    user_id: 'u1',
    full_name: 'Carlos Mendes',
    document: '123.456.789-00',
    cnh: '01234567890',
    cnh_category: 'E',
    phone: '(11) 98888-1111',
    city: 'Campinas',
    state: 'SP',
    rating_avg: 4.9,
    rating_count: 128,
    is_available: true,
    created_at: iso(40),
    updated_at: iso(1),
    deleted_at: null,
  },
  {
    id: 'd2',
    user_id: 'u2',
    full_name: 'Ana Paula Ribeiro',
    document: '987.654.321-00',
    cnh: '09876543210',
    cnh_category: 'E',
    phone: '(41) 97777-2222',
    city: 'Curitiba',
    state: 'PR',
    rating_avg: 4.8,
    rating_count: 96,
    is_available: true,
    created_at: iso(60),
    updated_at: iso(2),
    deleted_at: null,
  },
  {
    id: 'd3',
    user_id: 'u3',
    full_name: 'José da Silva',
    document: '456.789.123-00',
    cnh: '11223344556',
    cnh_category: 'C',
    phone: '(31) 96666-3333',
    city: 'Belo Horizonte',
    state: 'MG',
    rating_avg: 4.6,
    rating_count: 54,
    is_available: false,
    created_at: iso(20),
    updated_at: iso(0),
    deleted_at: null,
  },
]

export const mockVehicles: Vehicle[] = [
  {
    id: 'v1',
    owner_id: 'u1',
    plate: 'ABC1D23',
    brand: 'Volvo',
    model: 'FH 540',
    year: 2022,
    type: 'Carreta',
    capacity_kg: 32000,
    is_active: true,
    created_at: iso(30),
    updated_at: iso(5),
    deleted_at: null,
  },
  {
    id: 'v2',
    owner_id: 'u2',
    plate: 'EFG4H56',
    brand: 'Scania',
    model: 'R 450',
    year: 2021,
    type: 'Bitrem',
    capacity_kg: 45000,
    is_active: true,
    created_at: iso(45),
    updated_at: iso(10),
    deleted_at: null,
  },
  {
    id: 'v3',
    owner_id: 'u3',
    plate: 'IJK7L89',
    brand: 'Mercedes-Benz',
    model: 'Accelo 1016',
    year: 2020,
    type: 'VUC',
    capacity_kg: 6000,
    is_active: true,
    created_at: iso(15),
    updated_at: iso(3),
    deleted_at: null,
  },
]

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    user_id: 'demo',
    title: 'Nova candidatura',
    body: 'Carlos Mendes se candidatou à carga Soja a granel.',
    type: 'info',
    link: '/app/cargas/1',
    read_at: null,
    created_at: iso(0),
    updated_at: iso(0),
    deleted_at: null,
  },
  {
    id: 'n2',
    user_id: 'demo',
    title: 'Pagamento confirmado',
    body: 'Recebemos R$ 9.800,00 referente ao frete de açúcar.',
    type: 'success',
    link: '/app/financeiro',
    read_at: null,
    created_at: iso(1),
    updated_at: iso(1),
    deleted_at: null,
  },
  {
    id: 'n3',
    user_id: 'demo',
    title: 'Avaliação recebida',
    body: 'Você recebeu 5 estrelas de PartsMove.',
    type: 'success',
    link: '/app/avaliacoes',
    read_at: iso(2),
    created_at: iso(2),
    updated_at: iso(2),
    deleted_at: null,
  },
]

export const mockConversations: Conversation[] = [
  {
    id: 'm1',
    participant_ids: ['demo', 'u1'],
    load_id: '1',
    last_message: 'Posso coletar amanhã às 8h?',
    last_message_at: iso(0),
    unread_count: 2,
    participant_name: 'Carlos Mendes',
    participant_avatar: null,
  },
  {
    id: 'm2',
    participant_ids: ['demo', 'u2'],
    load_id: '2',
    last_message: 'Documentação do container enviada.',
    last_message_at: iso(1),
    unread_count: 0,
    participant_name: 'Ana Paula Ribeiro',
    participant_avatar: null,
  },
  {
    id: 'm3',
    participant_ids: ['demo', 'c3'],
    load_id: '4',
    last_message: 'Confirmado o valor combinado.',
    last_message_at: iso(2),
    unread_count: 1,
    participant_name: 'PartsMove',
    participant_avatar: null,
  },
]

export const mockPayments: Payment[] = [
  {
    id: 'p1',
    contract_id: 'ct1',
    amount: 9800,
    status: 'paid',
    method: 'PIX',
    paid_at: iso(7),
    created_at: iso(8),
    updated_at: iso(7),
    deleted_at: null,
  },
  {
    id: 'p2',
    contract_id: 'ct2',
    amount: 3200,
    status: 'pending',
    method: null,
    paid_at: null,
    created_at: iso(1),
    updated_at: iso(1),
    deleted_at: null,
  },
  {
    id: 'p3',
    contract_id: 'ct3',
    amount: 14500,
    status: 'paid',
    method: 'Transferência',
    paid_at: iso(3),
    created_at: iso(4),
    updated_at: iso(3),
    deleted_at: null,
  },
]

export const mockReviews: Review[] = [
  {
    id: 'r1',
    contract_id: 'ct1',
    reviewer_id: 'c2',
    reviewee_id: 'demo',
    rating: 5,
    comment: 'Entrega no prazo e comunicação excelente.',
    created_at: iso(6),
    updated_at: iso(6),
    deleted_at: null,
  },
  {
    id: 'r2',
    contract_id: 'ct3',
    reviewer_id: 'c3',
    reviewee_id: 'demo',
    rating: 4,
    comment: 'Boa experiência. Pequeno atraso na coleta.',
    created_at: iso(2),
    updated_at: iso(2),
    deleted_at: null,
  },
]

export const mockApplications: Record<string, ApplicationWithDriver[]> = {
  '1': [
    {
      id: 'a1',
      load_id: '1',
      driver_id: 'd1',
      vehicle_id: 'v1',
      message: 'Disponível a partir de amanhã cedo. Carreta com sider, experiência em granel.',
      proposed_price: 12500,
      status: 'pending',
      driver: { full_name: 'Carlos Mendes', city: 'Campinas', state: 'SP', rating_avg: 4.9, rating_count: 128 },
      created_at: iso(0),
      updated_at: iso(0),
      deleted_at: null,
    },
    {
      id: 'a2',
      load_id: '1',
      driver_id: 'd2',
      vehicle_id: 'v2',
      message: 'Posso coletar às 8h. Bitrem, documentação em dia.',
      proposed_price: 12200,
      status: 'pending',
      driver: { full_name: 'Ana Paula Ribeiro', city: 'Curitiba', state: 'PR', rating_avg: 4.8, rating_count: 96 },
      created_at: iso(1),
      updated_at: iso(1),
      deleted_at: null,
    },
    {
      id: 'a3',
      load_id: '1',
      driver_id: 'd3',
      vehicle_id: null,
      message: null,
      proposed_price: null,
      status: 'rejected',
      driver: { full_name: 'José da Silva', city: 'Belo Horizonte', state: 'MG', rating_avg: 4.6, rating_count: 54 },
      created_at: iso(2),
      updated_at: iso(1),
      deleted_at: null,
    },
  ],
  '3': [
    {
      id: 'a4',
      load_id: '3',
      driver_id: 'd3',
      vehicle_id: 'v3',
      message: 'Aceito, já estou a caminho da coleta.',
      proposed_price: 3200,
      status: 'accepted',
      driver: { full_name: 'José da Silva', city: 'Belo Horizonte', state: 'MG', rating_avg: 4.6, rating_count: 54 },
      created_at: iso(4),
      updated_at: iso(3),
      deleted_at: null,
    },
  ],
}

export const mockTrackingEvents: Record<string, TrackingEvent[]> = {
  '3': [
    {
      id: 't1',
      load_id: '3',
      status: 'accepted',
      description: 'Motorista José da Silva aceito para o frete.',
      location: null,
      created_at: iso(3),
      updated_at: iso(3),
      deleted_at: null,
    },
    {
      id: 't2',
      load_id: '3',
      status: 'pickup_scheduled',
      description: 'Coleta agendada com o embarcador.',
      location: 'Joinville/SC',
      created_at: iso(3),
      updated_at: iso(3),
      deleted_at: null,
    },
    {
      id: 't3',
      load_id: '3',
      status: 'collected',
      description: 'Carga coletada e conferida.',
      location: 'Joinville/SC',
      created_at: iso(2),
      updated_at: iso(2),
      deleted_at: null,
    },
    {
      id: 't4',
      load_id: '3',
      status: 'in_transit',
      description: 'Em trânsito para o destino.',
      location: 'Curitiba/PR',
      created_at: iso(1),
      updated_at: iso(1),
      deleted_at: null,
    },
  ],
  '5': [
    {
      id: 't5',
      load_id: '5',
      status: 'accepted',
      description: 'Motorista aceito para o frete.',
      location: null,
      created_at: iso(10),
      updated_at: iso(10),
      deleted_at: null,
    },
    {
      id: 't6',
      load_id: '5',
      status: 'collected',
      description: 'Carga coletada e conferida.',
      location: 'Ribeirão Preto/SP',
      created_at: iso(9),
      updated_at: iso(9),
      deleted_at: null,
    },
    {
      id: 't7',
      load_id: '5',
      status: 'in_transit',
      description: 'Em trânsito para o destino.',
      location: 'Curitiba/PR',
      created_at: iso(8),
      updated_at: iso(8),
      deleted_at: null,
    },
    {
      id: 't8',
      load_id: '5',
      status: 'delivered',
      description: 'Carga entregue e assinada pelo destinatário.',
      location: 'Porto Alegre/RS',
      created_at: iso(7),
      updated_at: iso(7),
      deleted_at: null,
    },
  ],
}

export const mockMapMarkers: MapMarker[] = [
  { id: '1', lat: -16.47, lng: -54.64, label: 'Rondonópolis (origem)', type: 'origin' },
  { id: '2', lat: -23.96, lng: -46.33, label: 'Santos (destino)', type: 'destination' },
  { id: '3', lat: -22.9, lng: -47.06, label: 'Carlos Mendes', type: 'driver' },
  { id: '4', lat: -25.43, lng: -49.27, label: 'Ana Paula', type: 'driver' },
  { id: '5', lat: -23.55, lng: -46.63, label: 'São Paulo (origem)', type: 'origin' },
]
